[package]
name = "sfc5xxx-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
serialport = "4.7.0"
sfc-core = {path="../sfc-core"}

[dev-dependencies]
serial_test = "3.2.0"
approx = "0.5.1"
